"""
EGX Name Mapping Generator

Auto-generates bilingual company name mapping from the EGX live feed's Arabic names
and cross-references with the existing egx_symbols.py database.

Outputs:
- JSON mapping file for import into app.js
- Updated COMPANY_NAMES entries for 200+ stocks
"""

import json
import os
import sys
import logging

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from egx_symbols import EGX_SYMBOL_DATABASE, get_stock_info

logger = logging.getLogger(__name__)

# Output path for generated mapping
OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_JSON = os.path.join(OUTPUT_DIR, 'company_names.json')
OUTPUT_JS = os.path.join(OUTPUT_DIR, 'company_names.js')


def generate_name_mapping(live_names=None):
    """
    Generate complete bilingual company name mapping.

    Merges data from:
    1. egx_symbols.py (curated EGX 30 names with English + Arabic)
    2. EGX live feed (200+ Arabic names for all traded stocks)

    Args:
        live_names: dict from egx_live_scraper.get_egx_names(), or None to skip live data

    Returns:
        dict: {symbol: {en: str, ar: str}} for all known stocks
    """
    mapping = {}

    # 1. Start with curated names from egx_symbols.py
    for ticker, stock in EGX_SYMBOL_DATABASE.items():
        symbol = stock.yahoo  # e.g., 'COMI.CA'
        mapping[symbol] = {
            'en': stock.name_en,
            'ar': stock.name_ar,
        }

    # 2. Merge live feed names (adds 200+ stocks, fills gaps)
    if live_names:
        for symbol, info in live_names.items():
            if symbol not in mapping:
                # New stock not in our curated database
                mapping[symbol] = {
                    'en': info.get('ticker', symbol.replace('.CA', '')),  # Fallback to ticker
                    'ar': info.get('name_ar', ''),
                }
            else:
                # Update Arabic name if our curated one is empty
                if not mapping[symbol]['ar'] and info.get('name_ar'):
                    mapping[symbol]['ar'] = info['name_ar']

    logger.info(f"Generated mapping for {len(mapping)} stocks")
    return mapping


def save_as_json(mapping, path=None):
    """Save mapping as JSON file."""
    path = path or OUTPUT_JSON
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(mapping, f, ensure_ascii=False, indent=2)
    logger.info(f"Saved JSON mapping to {path}")
    return path


def save_as_js_snippet(mapping, path=None):
    """
    Save mapping as a JavaScript snippet that can be pasted into app.js.

    Output format:
    const COMPANY_NAMES = {
        'COMI.CA': { en: 'Commercial International Bank (CIB)', ar: 'البنك التجاري الدولي' },
        ...
    };
    """
    path = path or OUTPUT_JS
    lines = ["// Auto-generated company name mapping (EGX + US stocks)",
             "// Generated by data/egx_name_mapping.py",
             f"// Last updated: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')}",
             "const COMPANY_NAMES = {"]

    # US stocks (hardcoded since they don't come from EGX feed)
    us_stocks = {
        'AAPL': {'en': 'Apple Inc.', 'ar': 'شركة أبل'},
        'GOOGL': {'en': 'Alphabet Inc. (Google)', 'ar': 'ألفابت (جوجل)'},
        'MSFT': {'en': 'Microsoft Corporation', 'ar': 'شركة مايكروسوفت'},
        'AMZN': {'en': 'Amazon.com Inc.', 'ar': 'شركة أمازون'},
        'META': {'en': 'Meta Platforms Inc.', 'ar': 'شركة ميتا'},
        'TSLA': {'en': 'Tesla Inc.', 'ar': 'شركة تسلا'},
        'NVDA': {'en': 'NVIDIA Corporation', 'ar': 'شركة إنفيديا'},
        'JPM': {'en': 'JPMorgan Chase & Co.', 'ar': 'جي بي مورغان'},
        'V': {'en': 'Visa Inc.', 'ar': 'شركة فيزا'},
        'JNJ': {'en': 'Johnson & Johnson', 'ar': 'جونسون آند جونسون'},
        'WMT': {'en': 'Walmart Inc.', 'ar': 'شركة وولمارت'},
        'XOM': {'en': 'Exxon Mobil Corporation', 'ar': 'إكسون موبيل'},
        'BAC': {'en': 'Bank of America Corp.', 'ar': 'بنك أوف أمريكا'},
        'PG': {'en': 'Procter & Gamble Co.', 'ar': 'بروكتر آند غامبل'},
        'HD': {'en': 'The Home Depot Inc.', 'ar': 'هوم ديبوت'},
    }

    lines.append("    // US Stocks")
    for symbol, names in us_stocks.items():
        lines.append(f"    '{symbol}': {{ en: '{names['en']}', ar: '{names['ar']}' }},")

    lines.append("    // EGX Stocks (Egyptian Exchange)")
    for symbol in sorted(mapping.keys()):
        names = mapping[symbol]
        en_name = names['en'].replace("'", "\\'")
        ar_name = names['ar'].replace("'", "\\'")
        lines.append(f"    '{symbol}': {{ en: '{en_name}', ar: '{ar_name}' }},")

    lines.append("};")

    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    logger.info(f"Saved JS snippet to {path}")
    return path


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    print("📝 Generating EGX company name mapping...")

    # Try to get live data
    live_names = None
    try:
        from data.egx_live_scraper import fetch_egx_live, get_egx_names
        print("  Fetching live feed for names...")
        df = fetch_egx_live()
        live_names = get_egx_names(df)
        print(f"  Got {len(live_names)} names from live feed")
    except Exception as e:
        print(f"  ⚠️  Could not fetch live data: {e}")
        print("  Using curated database only")

    # Generate mapping
    mapping = generate_name_mapping(live_names)
    print(f"\n✅ Generated mapping for {len(mapping)} stocks")

    # Save files
    json_path = save_as_json(mapping)
    js_path = save_as_js_snippet(mapping)

    print(f"\n📄 JSON: {json_path}")
    print(f"📄 JS snippet: {js_path}")

    # Preview
    print("\nSample entries:")
    for symbol in list(mapping.keys())[:10]:
        names = mapping[symbol]
        print(f"  {symbol}: {names['en']} / {names['ar']}")
